### ISSUE TITLE
Whole BTC price not being returned

### ISSUE THREAD

**Issue by indygill** [Formicka/exchangerate.host#133]
API Call
````HTTP
https://api.exchangerate.host/2022-05-17?source=crypto&amount=1&symbols=XRP,ETH,BTC&base=USD
````

Response
````JSON
// 20220518002111
// https://api.exchangerate.host/2022-05-17?source=crypto&amount=1&symbols=XRP,ETH,BTC&base=USD

{
  "motd": {
    "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
    "url": "https://exchangerate.host/#/donate"
  },
  "success": true,
  "historical": true,
  "base": "USD",
  "date": "2022-05-17",
  "rates": {
    "BTC": 0.000033,
    "XRP": 0.39059,
    "ETH": 1871.986008
  }
}
````

One whole coin price for XRP and ETH are returned, but not BTC?

**Comment by alerque** [comment]
The issue here is that ETH and others are inverted. The BTC value is correct. It is not showing "one whole BTC", it is showing the value of "1 whole USD" in BTC per your query. You should probably ask for more decimal places before you use that value too!

The confusing part is you are also seeing an invalid value, the ETH at least here is inverted, it is actually 1 ETH in USD — **NOT** what you asked for even if it is what you expected. This is a bug, see #37.

**Comment by indygill** [comment]
Duplicate. See @alerque comment above.
