### ISSUE TITLE
/latest?base=USD Error 521

### ISSUE THREAD

**Issue by maysaleba** [Formicka/exchangerate.host#90]
Hello, 

I'm getting an error as below when using a base rate
Error 521 Ray ID: 6cb2a942e9f9fb88 • 2022-01-10 03:01:31 UTC
Web server is down

**Comment by jimmyner** [comment]
Mine has the same symptoms as yours. 
https://api.exchangerate.host/convert
Error 521 Ray ID: 6cb336330a4f26c1 • 2022-01-10 04:37:44 UTC
I would also like to know the problem.

**Comment by azeteg** [comment]
Server appears to be down since at least Friday.

This will give a Cloudflare 521 error:
https://api.exchangerate.host/timeseries?start_date=2022-01-01&end_date=2020-01-10

Any cached queries are working, for example:
https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2020-01-04

**Comment by BertoNovell** [comment]
Hi,
Any news on this??? 

Thanks,
Best regards.

**Comment by sseBmoT** [comment]
Hello, 

We got the same problem in our application. Using a query or a non-cached request return error 521.
Posting here to keep updated on the issue.

Thanks,

**Comment by ignacio-dev** [comment]
I think they have fixed the issue now

**Comment by BertoNovell** [comment]
Thank you for fixing the issue!!! We really appreciate!!!
